---
title: "insurance-regression"
author: "Joseph Park"
date: "4/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## data and packages

```{r}

library(class)

library(tidyverse)

library(gmodels)

library(MLmetrics)

library(psych)
```

```{r}
insurance <- read.csv("C:/Users/parkj/OneDrive/Documents/joe/ML with R/insurance.csv", stringsAsFactors = TRUE)
```

```{r}
str(insurance)
```

```{r}
print(insurance[complete.cases(insurance) == FALSE, ])

print(which(is.na(insurance)))

```


```{r}
summary(insurance)

```
```{r}
for (i in c(1,3,4,7)){
  print(sd(as.matrix(insurance[,i])))
}
```

```{r}
for (i in c(1,3,4,7)){
  hist(as.matrix(insurance[,i]))
}
```

```{r}
cor(insurance[c("age", "bmi", "children", "charges")])
```
```{r}
pairs(insurance[c("age", "bmi", "children", "charges")])
```

```{r}
pairs.panels(insurance[c("age", "bmi", "children", "charges")])
```

## Fit the linear model

```{r}
ins_model <- lm(charges ~ ., data = insurance)

ins_model
```

## Evaluate Performance
```{r}
summary(ins_model)
```
```{r}

```


## Improve performance

```{r}
insurance$age2 <- insurance$age^2

insurance$bmi30 <- ifelse(insurance$bmi >= 30, 1, 0)

#new model that includes the above, the former making it nonlinear and the latter being included into a new interaction term (a term that is really three terms: each individually and then the interaction itself)
ins_model2 <- lm(charges ~ age + age2 + children + bmi + sex +
bmi30*smoker + region, data = insurance)

summary(ins_model2)
```
```{r}
#R^2 improved by about 0.115

```
